package com.channelpartner.model.response.SeviceProvider

data class GarageInformation(
    var account_holder_name: String,
    var account_number: String,
    var avg_rating: String,
    var bank_name: String,
    var branch_name: String,
    var channelPartnerId: Int,
    var channelPartnerName: String,
    var contact_address: String,
    var contact_city: String,
    var contact_email_id: String,
    var contact_landline: String,
    var contact_landmark: String,
    var contact_latitude: String,
    var contact_location: String,
    var contact_longitude: String,
    var contact_mobile: String,
    var contact_person_name: String,
    var contact_pincode: String,
    var contact_state: String,
    var date_of_establish: String,
    var distance_from_current_location: String,
    var garage_name: String,
    var ifsc_code: String,
    var mobile_number: String,
    var owner_first_name: String,
    var owner_last_name: String,
    var photo: String,
    var service_provider_id: Int,
    var service_provider_uniqueNumber: String,
    var total_count: Int
)