package com.channelpartner.model.response

data class DetailsXX(
    var address: String,
    var alternate_contact: String,
    var board_details: List<BoardDetail>,
    var city_id: String,
    var reg_number: String,
    var contact: String,
    var created_by: Int,
    var description: String,
    var email: String,
    var establishment_date: String,
    var image: String,
    var profile_photo: String,
    var introducer_name: String,
    var logo_path: String,
    var medium_details: List<MediumDetail>,
    var name: String,
    var other_speciality: String,
    var package_details: List<PackageDetailll>,
    var pincode: String,
    var standrad_details: List<StandradDetail>,
    var state: String,
    var std_other: String,
    var subjetc_speciality: List<SubjetcSpeciality>,
    var gallary_images: List<GalleryDataItem>,
    var course_details: List<CoursesData>,
    var teaching_exp: String,
    var tota_gst: Double,
    var total_amount: Double,
    var total_ihc: Double,
    var unique_no: String,
    var gender: String
)