package com.channelpartner.model.response

data class DetailsX(
    var channelPartnerId: Int,
    var account_holder_name: String,
    var account_number: String,
    var bank_name: String,
    var branch_name: String,
    var channelpartner_No: String,
    var address: String,
    var cityName: String,
    var email: String,
    var alternateContact: String,
    var contact_landmark: String,
//    var contactNo: String,
    var pincode: String,
    var stateName: String,
    var cp_ex_date: String,
    var cp_generation: String,
    var cp_introducer_id: Int,
    var introducerName: String,
    var cp_reg_date: String,
    var currentLevel: String,
    var current_reward_points: String,
    var dob: String,
    var firstName: String,
    var gender: String,
    var ifsc_code: String,
    var lastName: String,
    var contactNo: String,
    var pancard_number: String,
    var imageUrl: String,
    var qr_code_no: String,
    var total_reward_points: String,
    var used_reward_points: String,
    var description: String,
    var referCode: String,
    var parentId: String
)